name=xDuinoRails_DccCvMscWeb
version=1.0.0
author=xDuinoRails
maintainer=xDuinoRails
sentence=A library for RNDIS, MSC, and Web Server features on RP2040.
paragraph=Provides RNDIS network interface, Mass Storage Class (RAM Disk), and a Web Server using LwIP and TinyUSB.
category=Communication
url=https://github.com/xDuinoRails/xDuinoRails_DccCvMscWeb
architectures=rp2040
includes=xDuinoRails_DccCvMscWeb.h
