[env:seeed-xiao-rp2040]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino
; lib_deps = adafruit/Adafruit TinyUSB Library ; Removed to avoid conflict
; lib_ldf_mode = deep+ ; Reverted
build_flags =
    -DUSE_TINYUSB
    -DCFG_TUD_ECM_RNDIS=1
    -DCFG_TUD_MSC=1
    -DCFG_TUD_CDC=1
    -DCFG_TUD_NET_RNDIS=1
    -DLWIP_HTTPD=1
    -DLWIP_HTTPD_CUSTOM_FILES=1
    -DLWIP_HTTPD_DYNAMIC_HEADERS=1
    -Iinclude
test_port = /dev/null
