[env:see-xiao-rp2040]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino
lib_deps = adafruit/Adafruit TinyUSB Library
build_flags = -DUSE_TINYUSB -DCFG_TUD_NET_RNDIS=1
lib_extra_dirs = ../RNDIS_USB/src
test_port = /dev/null
